### ISSUE TITLE
Veinminer Enchantment Incompatible with Purpur

### ISSUE THREAD

**Issue by LordOfTheWeebs** [MiraculixxT/Veinminer#10]
When attempting to load the Veinminer Enchantment plugin on my Purpur (1.21.1-2308) test server, it throws an error and isn't enabled. Testing on the exact same server but using the Paper jar file (1.21.1-82) instead of Purpur yields no such error. If possible, I recommend either adding Purpur support or removing Purpur support from the current uploaded version on Modrinth.

> [01:57:04 ERROR]: [BootstrapProviderStorage] Failed to run bootstrapper for plugins/veinminer-enchant-2.1.4.jar. This plugin will not be loaded.
> java.lang.NoSuchFieldError: Class io.papermc.paper.plugin.lifecycle.event.types.LifecycleEvents does not have member field 'io.papermc.paper.plugin.lifecycle.event.types.TagEventTypeProvider TAGS'
> 	at veinminer-enchant-2.1.4.jar/de.miraculixx.veinminerEnchant.paper.VeinminerEnchantmentBootstrapper.bootstrap(VeinminerEnchantmentBootstrapper.java:44) ~[veinminer-enchant-2.1.4.jar:?]
> 	at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:36) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
> 	at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:24) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
> 	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:117) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
> 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
> 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
> 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enterBootstrappers(LaunchEntryPointHandler.java:30) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
> 	at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:65) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
> 	at net.minecraft.server.Main.main(Main.java:130) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
> 	at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
> 	at org.bukkit.craftbukkit.Main.main(Main.java:295) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
> 	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
> 	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by LordOfTheWeebs** [comment]
Never mind, I'm an idiot who can't read, I had an outdated Purpur version and it works fine on the most recent.
