### ISSUE TITLE
Incompatible with Simple Voice Chat (Outdated Fabric Permissions API?)

### ISSUE THREAD

**Issue by bloofirephoenix** [MiraculixxT/Veinminer#17]
When using Simple Voice Chat along with Veinminer, I am getting the following console error multiple times per second:
```
[15:54:39] [VoiceChatPacketProcessingThread/WARN]: [voicechat] Failed to use fabric-permissions-api-v0
java.lang.NoSuchMethodError: 'net.minecraft.class_2168 net.minecraft.class_1297.method_5671()'
        at knot/me.lucko.fabric.api.permissions.v0.Permissions.check(Permissions.java:161) ~[fabric-permissions-api-v0-0.2-SNAPSHOT-4dccd28795ed08cf.jar:?]
        at knot/de.maxhenkel.voicechat.permission.FabricPermissionManager$1.hasPermission(FabricPermissionManager.java:17) [voicechat-fabric-1.21.4-2.5.26.jar:?]
        at knot/de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:433) [voicechat-fabric-1.21.4-2.5.26.jar:?]
        at knot/de.maxhenkel.voicechat.voice.server.Server.processGroupPacket(Server.java:374) [voicechat-fabric-1.21.4-2.5.26.jar:?]
        at knot/de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:347) [voicechat-fabric-1.21.4-2.5.26.jar:?]
        at knot/de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:340) [voicechat-fabric-1.21.4-2.5.26.jar:?]
        at knot/de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:307) [voicechat-fabric-1.21.4-2.5.26.jar:?]
```

I initially reported this to Simple Voice Chat and they have told me that another mod is shipping with "an outdated version of the fabric permissions API". Process of elimination leads to believe this mod is the culprit.

**Comment by MiraculixxT** [comment]
Indeed, i did not update the version of the embedded fabric permission API for a while now, as it was good enough for the limited use in Veinminer. You can overwrite the version by installing the latest version to your server, the embedded is only used if no version exists.
